### ISSUE TITLE
Issue When Searching for a Company

### ISSUE THREAD

**Issue by kevbite** [LiberisLabs/CompaniesHouse.NET#1]
When searching for a company the following exception is being thrown:

```
Newtonsoft.Json.JsonReaderException occurred
  HResult=-2146233088
  LineNumber=1
  LinePosition=510
  Message=Could not convert string to DateTime: Unknown. Path 'items[0].date_of_cessation', line 1, position 510.
  Path=items[0].date_of_cessation
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.JsonReader.ReadAsDateTimeInternal()
       at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
       at System.Net.Http.Formatting.JsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
       at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
       at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at LiberisLabs.CompaniesHouse.CompaniesHouseSearchCompanyClient.<SearchCompanyAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

```

The following search search request is being passed in:
```csharp
            var companySearchRequest = new CompanySearchRequest()
            {
                Query = "f",
                ItemsPerPage = 5
            };
```

**Comment by kevbite** [comment]
Just a bit of investigation and it seem that the response for date_of_cessation set to "Unknown" (see below) We'll need to create a custom Json Converter for this.

```javascript
{
  "kind": "search#companies",
  "total_results": 1,
  "items": [
    {
      "description": "04274383 - Dissolved on ",
      "date_of_creation": "2001-08-21",
      "description_identifier": [
        "dissolved-on"
      ],
      "links": {
        "self": "/company/04274383"
      },
      "address": {
        "postal_code": "S11 9PS",
        "address_line_1": "The Annexe The Manor House",
        "locality": "Sheffield",
        "address_line_2": "260 Ecclesall Road South"
      },
      "snippet": "The Annexe The Manor House, 260 Ecclesall Road South, Sheffield, S11 9PS",
      "company_number": "04274383",
      "kind": "searchresults#company",
      "title": "F LIMITED",
      "company_status": "dissolved",
      "company_type": "ltd",
      "date_of_cessation": "Unknown"
    }
  ],
  "start_index": 0,
  "page_number": 1,
  "items_per_page": 20
}
```
